Traceback (most recent call last):
  File "/home/mayi/anaconda3/envs/zzy_DIR/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/mayi/anaconda3/envs/zzy_DIR/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/mayi/data/zzy/DIR-GNN/train/cora.py", line 709, in <module>
    loss = train()
  File "/home/mayi/data/zzy/DIR-GNN/train/cora.py", line 585, in train
    out = model(data)
  File "/home/mayi/anaconda3/envs/zzy_DIR/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mayi/anaconda3/envs/zzy_DIR/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mayi/data/zzy/DIR-GNN/train/cora.py", line 436, in forward
    x = conv(x, edge_index)
  File "/home/mayi/anaconda3/envs/zzy_DIR/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mayi/anaconda3/envs/zzy_DIR/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mayi/data/zzy/DIR-GNN/train/cora.py", line 483, in forward
    x2 = self.conv2(x, edge_index)
  File "/home/mayi/anaconda3/envs/zzy_DIR/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mayi/anaconda3/envs/zzy_DIR/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mayi/anaconda3/envs/zzy_DIR/lib/python3.9/site-packages/torch_geometric/nn/conv/gatv2_conv.py", line 298, in forward
    alpha = self.edge_updater(edge_index, x=(x_l, x_r),
  File "/tmp/torch_geometric.nn.conv.gatv2_conv_GATv2Conv_edge_updater_6z7h820n.py", line 169, in edge_updater
    out = self.edge_update(
  File "/home/mayi/anaconda3/envs/zzy_DIR/lib/python3.9/site-packages/torch_geometric/nn/conv/gatv2_conv.py", line 328, in edge_update
    x = x_i + x_j
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 372.00 MiB. GPU 
Seed:  0
PMPGNN(
  (convs): ModuleList(
    (0): ParallelGNNBlock(
      (conv1): GATv2Conv(128, 128, heads=8)
      (conv2): GATv2Conv(128, 128, heads=8)
      (norm): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
    )
    (1-11): 11 x ParallelGNNBlock(
      (conv1): GATv2Conv(2048, 128, heads=8)
      (conv2): GATv2Conv(2048, 128, heads=8)
      (norm): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
    )
  )
  (norm): LayerNorm((2048,), eps=1e-05, elementwise_affine=True)
  (mlp): Sequential(
    (0): Linear(in_features=2048, out_features=64, bias=True)
    (1): LeakyReLU(negative_slope=0.01)
    (2): Dropout(p=0.3, inplace=False)
    (3): Linear(in_features=64, out_features=7, bias=True)
  )
  (proj): Linear(in_features=1433, out_features=128, bias=True)
)
